export interface FlagSettings {
  segmentsX: number;
  segmentsY: number;
  solverIterations: number;
  stiffness: number;
  windStrength: number;
  windTurbulence: number;
  windDirectionX: number;
  windDirectionY: number;
  windDirectionZ: number;
  zoneAStrength: number;
  zoneARadius: number;
  zoneASpeed: number;
  zoneADirX: number;
  zoneADirY: number;
  zoneADirZ: number;
  zoneBStrength: number;
  zoneBRadius: number;
  zoneBSpeed: number;
  zoneBDirX: number;
  zoneBDirY: number;
  zoneBDirZ: number;
  dampening: number;
  gravity: number;
  flagColor: string;
  roughness: number;
  sheen: number;
  sheenRoughness: number;
  emissiveIntensity: number;
  exposure: number;
  ambientIntensity: number;
  hemiIntensity: number;
  keyLightIntensity: number;
  fillLightIntensity: number;
  backLightIntensity: number;
  rimLightIntensity: number;
}

export const defaultFlagSettings = (): FlagSettings => ({
  segmentsX: 32,
  segmentsY: 12,
  solverIterations: 6,
  stiffness: 0.28,
  windStrength: 3.5,
  windTurbulence: 1.4,
  windDirectionX: 0,
  windDirectionY: 0,
  windDirectionZ: 1,
  zoneAStrength: 1.2,
  zoneARadius: 1.1,
  zoneASpeed: 0.65,
  zoneADirX: 1,
  zoneADirY: 0.05,
  zoneADirZ: 0.25,
  zoneBStrength: 0.9,
  zoneBRadius: 0.9,
  zoneBSpeed: 0.35,
  zoneBDirX: -0.8,
  zoneBDirY: 0.08,
  zoneBDirZ: 0.35,
  dampening: 0.993,
  gravity: 0.00003,
  flagColor: '#e82845',
  roughness: 0.55,
  sheen: 0.9,
  sheenRoughness: 0.28,
  emissiveIntensity: 0.18,
  exposure: 1.45,
  ambientIntensity: 0.75,
  hemiIntensity: 1.1,
  keyLightIntensity: 2.0,
  fillLightIntensity: 1.35,
  backLightIntensity: 1.25,
  rimLightIntensity: 0.95,
});
