export interface InextensibleFlagSettings {
  segmentsX: number;
  segmentsY: number;
  constraintIterations: number;
  bendStiffness: number;
  minCompression: number;
  clothThickness: number;
  /** Render mesh subdivisions per sim quad (physics grid unchanged). */
  renderSubdivisions: number;
  /** 0 = linear, 1 = Catmull-Rom, 2–3 = extra surface relaxation passes. */
  renderGeometrySmoothing: number;
  flatShading: boolean;
  selfCollision: boolean;
  poleCollision: boolean;
  windStrength: number;
  windTurbulence: number;
  windDirectionX: number;
  windDirectionY: number;
  windDirectionZ: number;
  zoneAStrength: number;
  zoneARadius: number;
  zoneASpeed: number;
  zoneADirX: number;
  zoneADirY: number;
  zoneADirZ: number;
  zoneBStrength: number;
  zoneBRadius: number;
  zoneBSpeed: number;
  zoneBDirX: number;
  zoneBDirY: number;
  zoneBDirZ: number;
  dampening: number;
  gravity: number;
  flagColor: string;
  roughness: number;
  sheen: number;
  sheenRoughness: number;
  emissiveIntensity: number;
  exposure: number;
  ambientIntensity: number;
  hemiIntensity: number;
  keyLightIntensity: number;
  fillLightIntensity: number;
  backLightIntensity: number;
  rimLightIntensity: number;
}

export const defaultInextensibleFlagSettings = (): InextensibleFlagSettings => ({
  segmentsX: 49,
  segmentsY: 26,
  constraintIterations: 7,
  bendStiffness: 0.01,
  minCompression: 0.92,
  clothThickness: 0.015,
  renderSubdivisions: 4,
  renderGeometrySmoothing: 1.5,
  flatShading: false,
  selfCollision: true,
  poleCollision: true,
  windStrength: 2.5,
  windTurbulence: 3.75,
  windDirectionX: -0.5,
  windDirectionY: 0.51,
  windDirectionZ: 0.85,
  zoneAStrength: 1.0,
  zoneARadius: 1.1,
  zoneASpeed: 0.65,
  zoneADirX: 1,
  zoneADirY: 0.05,
  zoneADirZ: 0.25,
  zoneBStrength: 0.85,
  zoneBRadius: 0.9,
  zoneBSpeed: 0.35,
  zoneBDirX: -0.8,
  zoneBDirY: 0.08,
  zoneBDirZ: 0.35,
  dampening: 0.9925,
  gravity: 0.00006,
  flagColor: '#e82845',
  roughness: 0.55,
  sheen: 0.9,
  sheenRoughness: 0.28,
  emissiveIntensity: 0.18,
  exposure: 1.45,
  ambientIntensity: 0.75,
  hemiIntensity: 1.1,
  keyLightIntensity: 2.0,
  fillLightIntensity: 1.35,
  backLightIntensity: 1.25,
  rimLightIntensity: 0.95,
});
